import test from "node:test"; import assert from "node:assert/strict";
import { buildGrievanceDraft, createOfficerSession, findExactDemoRegistryRecord, GRIEVANCE_NOTICE, redactAggregateRows, redactOfficerAnalysisCostRows, redactOfficerCostSummary, verifyOfficerSession } from "../src/public-services/index.ts";

test("registry requires an exact normalized identifier and never fuzzy matches",()=>{assert.equal(findExactDemoRegistryRecord(" 10000000000001 ")?.displayName,"Annapurna Foods Demo");assert.equal(findExactDemoRegistryRecord("1000000000000"),null);assert.equal(findExactDemoRegistryRecord("Annapurna Foods"),null)});
test("grievance is an editable non-submitting draft routed by allow-listed service",()=>{const draft=buildGrievanceDraft({product:"Demo pack",issue:"Missing date",purchaseDetails:"Local shop",requestedResolution:"Replacement",serviceId:"in.consumer-affairs.nch.v1"});assert.match(draft,/Demo pack/);assert.match(draft,new RegExp(GRIEVANCE_NOTICE.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.doesNotMatch(draft,/docket|submitted successfully/i);assert.throws(()=>buildGrievanceDraft({product:"",issue:"",purchaseDetails:"",requestedResolution:"",serviceId:"invented"}))});
test("officer signed sessions verify and expire",async()=>{const token=await createOfficerSession("demo","long-secret",1_000_000);assert.equal(await verifyOfficerSession(token,"long-secret",1_001_000),true);assert.equal(await verifyOfficerSession(token,"wrong-secret",1_001_000),false);assert.equal(await verifyOfficerSession(token,"long-secret",1_000_000+4*60*60*1000),false)});
test("aggregate redaction exposes only status language and numeric count",()=>{assert.deepEqual(redactAggregateRows([{status:"complete",language:"hi",count:3,image_hash:"secret",result_json:"secret"},{status:"failed",language:"en",count:"2"}]),[{status:"complete",language:"hi",count:3}])});
test("officer cost telemetry is strictly allow-listed and preserves unknown cost",()=>{const rows=redactOfficerAnalysisCostRows([{completed_at:"2026-08-24T10:00:00.000Z",status:"complete",language:"en",model_id:"gpt-5.6-terra",service_tier:"default",input_tokens:100,cached_input_tokens:20,cache_write_tokens:0,output_tokens:40,reasoning_tokens:10,total_tokens:140,web_search_calls:2,provider_duration_ms:4300,estimated_cost_usd_micros:null,cost_basis_version:null,image_hash:"secret",result_json:"secret",openai_response_id:"secret"}]);assert.deepEqual(rows,[{completedAt:"2026-08-24T10:00:00.000Z",status:"complete",language:"en",modelId:"gpt-5.6-terra",serviceTier:"default",inputTokens:100,cachedInputTokens:20,cacheWriteTokens:0,outputTokens:40,reasoningTokens:10,totalTokens:140,webSearchCalls:2,providerDurationMs:4300,estimatedCostUsdMicros:null,costBasisVersion:null}]);assert.equal("imageHash" in rows[0],false);assert.deepEqual(redactOfficerCostSummary({completed_analyses:4,costed_analyses:2,total_cost_usd_micros:50000,input_tokens:1000,output_tokens:200,web_search_calls:3}),{completedAnalyses:4,costedAnalyses:2,totalCostUsdMicros:50000,averageCostUsdMicros:25000,inputTokens:1000,outputTokens:200,webSearchCalls:3})});
test("officer aggregate spend stays unknown when no completed run has cost telemetry",()=>{assert.equal(redactOfficerCostSummary({completed_analyses:3,costed_analyses:0,total_cost_usd_micros:0}).totalCostUsdMicros,null)});
